name: SciPhi_root
title: "Sci-Phi: A Large Language Model Spatial Audio Descriptor"
url: "https://sci-phi-audio.github.io"
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme
