name: AAD-LLM_root
title: "AAD-LLM: Neural Attention-Driven Auditory Scene Understanding"
url: "https://aad-llm.github.io"
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme
